services:
  api:
    build: DjangoRestApi/
    image: frasp/djangorestapi:latest
    container_name: djangorestapi
    environment:
      - CORS_ALLOWED_ORIGINS=http://localhost:8080
    ports:
      - "4848:8000"
    volumes:
      - api:/app/storage
    networks:
      - pd421_gameshop

  front:
    build: my-vite/
    image: frasp/my-vite:latest
    container_name: my-vite
    depends_on:
      - api
    ports:
      - "80:8080"
    networks:
      - pd421_gameshop
    environment:
      - BASE_URL=http://localhost:8000/api

networks:
  pd421_gameshop:
    name: "pd421_gameshop"

volumes:
  api:
    driver: local
    name: "api"