services:
  api:
    build:
      context: DjangoRestApi/atbapi
      dockerfile: Dockerfile
    image: frasp/djangorestapi:latest
    container_name: djangorestapi
    environment:
      - CORS_ALLOWED_ORIGINS=http://localhost:8080
    ports:
      - "8000:8000"
    volumes:
      - api:/app/storage
    networks:
      - pd421_gameshop

  front:
    build:
      context: my-vite/
      args:
       BASE_URL: http://localhost:8000/
    image: frasp/my-vite:latest
    container_name: my-vite
    depends_on:
      - api
    ports:
      - "8080:8080"
    networks:
      - pd421_gameshop
    

networks:
  pd421_gameshop:
    name: "pd421_gameshop"

volumes:
  api:
    driver: local
    name: "api"
